#cloud-config

package_update: true

packages:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - mc
  - openjdk-17-jre
  - git
  - htop

runcmd:
  # Adicionar chave GPG oficial do Docker e repositório
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  # Atualizar lista de pacotes e instalar Docker Engine
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io

  # Iniciar e habilitar o serviço Docker
  - systemctl start docker.service
  - systemctl enable docker.service

  # Adicionar o usuário 'root' ao grupo Docker
  - usermod -aG docker $USER

  # Configurar o repositório e instalar o Jenkins
  - wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
  - sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - apt-get update
  - apt-get install -y jenkins

  # Adicionar o usuário 'jenkins' ao grupo Docker
  - usermod -aG docker jenkins

  # Reiniciar o serviço Jenkins
  - systemctl restart jenkins
  - reboot
