#cloud-config

package_update: true

packages:
  - curl
  - apt-transport-https
  - docker.io
  - mc
  - openjdk-17-jre
  - git
  - htop

runcmd:
  # Configurar o repositório e instalar o Jenkins
  - wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
  - sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - apt-get update && apt-get install jenkins -y

  # Iniciar e habilitar o serviço Docker
  - systemctl start docker.service
  - systemctl enable docker.service

  # Instalar o Docker Compose (v2.26.0 para ARM64)
  - mkdir -p /usr/local/lib/docker/cli-plugins/
  - curl -SL "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-linux-aarch64" -o /usr/local/lib/docker/cli-plugins/docker-compose
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose

  # Adicionar o usuário Jenkins ao grupo Docker
  - usermod -aG docker jenkins

  # Reiniciar o serviço Jenkins
  - systemctl restart jenkins
