version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq

  ravendb:
    image: ravendb/ravendb:ubuntu-latest
    environment:
      RAVEN_Setup_Mode: "None"
      RAVEN_License_Eula_Accepted: "true"
    ports:
      - "8080:8080"
#     volumes:
#       - data:/opt/RavenDB/Server/RavenData

# volumes:
#   data:
    # rabbitmq_data: