version: '3.8'

services:
  ansible:
    build: .
    container_name: ansible-container
    volumes:
      - ../.ssh:/root/.ssh
      - .:/ansible
    working_dir: /ansible
    command: /bin/bash -c "chmod 600 /root/.ssh/id_ed25519 && sleep infinity"
