version: '3.8'

services:
  ansible:
    build: .
    container_name: ansible-container
    volumes:
      - ../.ssh:/root/.ssh
      - .:/ansible
    env_file:
      - .env
    working_dir: /ansible
    command: /bin/bash -c "/entrypoint.sh && sleep infinity"