version: '3.8'

services:
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - rabbitmq_data:/var/lib/rabbitmq

# volumes:
#   rabbitmq_data:
